//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portafolio
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLETA
    {
        public BOLETA()
        {
            this.DETALLE_BOLETA = new HashSet<DETALLE_BOLETA>();
            this.FIADO1 = new HashSet<FIADO>();
        }
    
        public decimal NUMERO_BOLETA { get; set; }
        public short FIADO { get; set; }
        public string TIPO_PAGO { get; set; }
        public decimal TOTAL_BOLETA { get; set; }
        public System.DateTime FECHA_BOLETA { get; set; }
        public decimal ID_CLIENTE { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ICollection<DETALLE_BOLETA> DETALLE_BOLETA { get; set; }
        public virtual ICollection<FIADO> FIADO1 { get; set; }
    }
}
