//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portafolio
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIADO
    {
        public decimal ID_FIADO { get; set; }
        public decimal MONTO_SOLICITADO { get; set; }
        public decimal MONTO_PAGADO { get; set; }
        public System.DateTime FECHA_COMPRA { get; set; }
        public System.DateTime FECHA_PAGO { get; set; }
        public string ESTADO_PAGO { get; set; }
        public decimal ID_CLIENTE { get; set; }
        public decimal ID_BOLETA { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual BOLETA BOLETA { get; set; }
    }
}
