//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portafolio
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.DETALLE_BOLETA = new HashSet<DETALLE_BOLETA>();
            this.PEDIDO = new HashSet<PEDIDO>();
            this.RECEPCION = new HashSet<RECEPCION>();
        }
    
        public decimal ID_PRODUCTO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal PRECIO_VENTA { get; set; }
        public string UNIDAD_MEDIDA { get; set; }
        public decimal STOCK { get; set; }
        public System.DateTime FECHA_VENCIMIENTO { get; set; }
        public decimal PRECIO_COMPRA { get; set; }
        public decimal STOCK_CRITICO { get; set; }
        public decimal ID_PROVEEDOR { get; set; }
        public decimal ID_TIPO_PRODUCTO { get; set; }
        public decimal ID_TIPO_MONEDA { get; set; }
    
        public virtual ICollection<DETALLE_BOLETA> DETALLE_BOLETA { get; set; }
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual TIPO_MONEDA TIPO_MONEDA { get; set; }
        public virtual TIPO_PRODUCTO TIPO_PRODUCTO { get; set; }
        public virtual ICollection<RECEPCION> RECEPCION { get; set; }
    }
}
