//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portafolio
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        public PROVEEDOR()
        {
            this.PEDIDO = new HashSet<PEDIDO>();
            this.PRODUCTO = new HashSet<PRODUCTO>();
            this.RECEPCION = new HashSet<RECEPCION>();
        }
    
        public decimal ID_PROVEEDOR { get; set; }
        public string RUT_PROVEEDOR { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public decimal FONO { get; set; }
        public string EMAIL { get; set; }
        public string GIRO { get; set; }
        public Nullable<short> ESTADO { get; set; }
    
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
        public virtual ICollection<RECEPCION> RECEPCION { get; set; }
    }
}
